--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_profile (
    id bigint NOT NULL,
    phone character varying(32) NOT NULL,
    bio text NOT NULL,
    avatar character varying(100),
    location character varying(120) NOT NULL,
    farm_name character varying(120) NOT NULL,
    preferred_language character varying(32) NOT NULL,
    email_verified boolean NOT NULL,
    last_seen timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: accounts_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_activitylog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_activitylog (
    id bigint NOT NULL,
    action character varying(160) NOT NULL,
    metadata jsonb NOT NULL,
    ip_address inet,
    user_agent text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer
);


--
-- Name: core_activitylog_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_activitylog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_activitylog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_contactmessage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_contactmessage (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    email character varying(254) NOT NULL,
    subject character varying(160) NOT NULL,
    message text NOT NULL,
    is_resolved boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: core_contactmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_contactmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_contactmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_crop; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_crop (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    scientific_name character varying(160) NOT NULL,
    description text NOT NULL,
    growing_conditions text NOT NULL,
    image character varying(100),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: core_crop_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_crop ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_crop_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_disease; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_disease (
    id bigint NOT NULL,
    name character varying(160) NOT NULL,
    slug character varying(50) NOT NULL,
    description text NOT NULL,
    symptoms text NOT NULL,
    causes text NOT NULL,
    treatment text NOT NULL,
    prevention text NOT NULL,
    severity character varying(16) NOT NULL,
    image character varying(100),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    crop_id bigint,
    needs_content boolean NOT NULL,
    raw_class_name character varying(160) NOT NULL
);


--
-- Name: core_disease_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_disease ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_disease_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_faq; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_faq (
    id bigint NOT NULL,
    question character varying(255) NOT NULL,
    answer text NOT NULL,
    category character varying(120) NOT NULL,
    "order" integer NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT core_faq_order_check CHECK (("order" >= 0))
);


--
-- Name: core_faq_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_faq ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_faq_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_feedback (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    email character varying(254) NOT NULL,
    rating smallint NOT NULL,
    subject character varying(160) NOT NULL,
    message text NOT NULL,
    is_published boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer,
    CONSTRAINT core_feedback_rating_check CHECK ((rating >= 0))
);


--
-- Name: core_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_notification (
    id bigint NOT NULL,
    title character varying(160) NOT NULL,
    message text NOT NULL,
    link character varying(200) NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: core_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detection_prediction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.detection_prediction (
    id bigint NOT NULL,
    confidence_score double precision NOT NULL,
    confidence_level character varying(10) NOT NULL,
    is_healthy boolean NOT NULL,
    predicted_at timestamp with time zone NOT NULL,
    model_version character varying(50) NOT NULL,
    processing_time double precision NOT NULL,
    crop_id bigint,
    disease_id bigint,
    scan_image_id bigint NOT NULL,
    analysis_image character varying(100),
    effnet_top_confidence double precision NOT NULL,
    effnet_top_label character varying(160) NOT NULL,
    is_uncertain boolean NOT NULL,
    yolo_top_confidence double precision NOT NULL,
    yolo_top_label character varying(160) NOT NULL
);


--
-- Name: detection_prediction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.detection_prediction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detection_prediction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detection_scanimage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.detection_scanimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    is_processed boolean NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: detection_scanimage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.detection_scanimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detection_scanimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: history_predictionhistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.history_predictionhistory (
    id bigint NOT NULL,
    notes text NOT NULL,
    tags character varying(255) NOT NULL,
    is_archived boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    prediction_id bigint NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: history_predictionhistory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.history_predictionhistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.history_predictionhistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendation_recommendation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommendation_recommendation (
    id bigint NOT NULL,
    treatment_steps text NOT NULL,
    prevention_steps text NOT NULL,
    urgency character varying(10) NOT NULL,
    additional_notes text NOT NULL,
    expert_reviewed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    disease_id bigint,
    prediction_id bigint NOT NULL,
    reviewed_by_id integer,
    ai_content jsonb NOT NULL,
    ai_content_generated_at timestamp with time zone,
    ai_generation_error text NOT NULL
);


--
-- Name: recommendation_recommendation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recommendation_recommendation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendation_recommendation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendation_userfeedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommendation_userfeedback (
    id bigint NOT NULL,
    feedback_type character varying(20) NOT NULL,
    comment text NOT NULL,
    rating integer,
    created_at timestamp with time zone NOT NULL,
    recommendation_id bigint NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: recommendation_userfeedback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recommendation_userfeedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendation_userfeedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_profile accounts_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_pkey PRIMARY KEY (id);


--
-- Name: accounts_profile accounts_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_activitylog core_activitylog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_activitylog
    ADD CONSTRAINT core_activitylog_pkey PRIMARY KEY (id);


--
-- Name: core_contactmessage core_contactmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_contactmessage
    ADD CONSTRAINT core_contactmessage_pkey PRIMARY KEY (id);


--
-- Name: core_crop core_crop_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_crop
    ADD CONSTRAINT core_crop_name_key UNIQUE (name);


--
-- Name: core_crop core_crop_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_crop
    ADD CONSTRAINT core_crop_pkey PRIMARY KEY (id);


--
-- Name: core_disease core_disease_crop_id_name_33246470_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_disease
    ADD CONSTRAINT core_disease_crop_id_name_33246470_uniq UNIQUE (crop_id, name);


--
-- Name: core_disease core_disease_crop_id_slug_745c8cb4_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_disease
    ADD CONSTRAINT core_disease_crop_id_slug_745c8cb4_uniq UNIQUE (crop_id, slug);


--
-- Name: core_disease core_disease_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_disease
    ADD CONSTRAINT core_disease_pkey PRIMARY KEY (id);


--
-- Name: core_faq core_faq_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_faq
    ADD CONSTRAINT core_faq_pkey PRIMARY KEY (id);


--
-- Name: core_feedback core_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_feedback
    ADD CONSTRAINT core_feedback_pkey PRIMARY KEY (id);


--
-- Name: core_notification core_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_notification
    ADD CONSTRAINT core_notification_pkey PRIMARY KEY (id);


--
-- Name: detection_prediction detection_prediction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detection_prediction
    ADD CONSTRAINT detection_prediction_pkey PRIMARY KEY (id);


--
-- Name: detection_prediction detection_prediction_scan_image_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detection_prediction
    ADD CONSTRAINT detection_prediction_scan_image_id_key UNIQUE (scan_image_id);


--
-- Name: detection_scanimage detection_scanimage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detection_scanimage
    ADD CONSTRAINT detection_scanimage_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: history_predictionhistory history_predictionhistory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.history_predictionhistory
    ADD CONSTRAINT history_predictionhistory_pkey PRIMARY KEY (id);


--
-- Name: history_predictionhistory history_predictionhistory_prediction_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.history_predictionhistory
    ADD CONSTRAINT history_predictionhistory_prediction_id_key UNIQUE (prediction_id);


--
-- Name: recommendation_recommendation recommendation_recommendation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_recommendation
    ADD CONSTRAINT recommendation_recommendation_pkey PRIMARY KEY (id);


--
-- Name: recommendation_recommendation recommendation_recommendation_prediction_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_recommendation
    ADD CONSTRAINT recommendation_recommendation_prediction_id_key UNIQUE (prediction_id);


--
-- Name: recommendation_userfeedback recommendation_userfeedb_recommendation_id_user_i_6348def8_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_userfeedback
    ADD CONSTRAINT recommendation_userfeedb_recommendation_id_user_i_6348def8_uniq UNIQUE (recommendation_id, user_id);


--
-- Name: recommendation_userfeedback recommendation_userfeedback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_userfeedback
    ADD CONSTRAINT recommendation_userfeedback_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: core_activitylog_user_id_8705e516; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_activitylog_user_id_8705e516 ON public.core_activitylog USING btree (user_id);


--
-- Name: core_crop_name_18374990_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_crop_name_18374990_like ON public.core_crop USING btree (name varchar_pattern_ops);


--
-- Name: core_disease_crop_id_44be9f47; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_disease_crop_id_44be9f47 ON public.core_disease USING btree (crop_id);


--
-- Name: core_disease_slug_082906f4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_disease_slug_082906f4 ON public.core_disease USING btree (slug);


--
-- Name: core_disease_slug_082906f4_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_disease_slug_082906f4_like ON public.core_disease USING btree (slug varchar_pattern_ops);


--
-- Name: core_feedback_user_id_630c6a53; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_feedback_user_id_630c6a53 ON public.core_feedback USING btree (user_id);


--
-- Name: core_notification_user_id_6e341aac; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_notification_user_id_6e341aac ON public.core_notification USING btree (user_id);


--
-- Name: detection_prediction_crop_id_94368a84; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX detection_prediction_crop_id_94368a84 ON public.detection_prediction USING btree (crop_id);


--
-- Name: detection_prediction_disease_id_48775137; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX detection_prediction_disease_id_48775137 ON public.detection_prediction USING btree (disease_id);


--
-- Name: detection_scanimage_user_id_44e0895f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX detection_scanimage_user_id_44e0895f ON public.detection_scanimage USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: history_predictionhistory_user_id_fb641484; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX history_predictionhistory_user_id_fb641484 ON public.history_predictionhistory USING btree (user_id);


--
-- Name: recommendation_recommendation_disease_id_d327a144; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recommendation_recommendation_disease_id_d327a144 ON public.recommendation_recommendation USING btree (disease_id);


--
-- Name: recommendation_recommendation_reviewed_by_id_2f4297d3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recommendation_recommendation_reviewed_by_id_2f4297d3 ON public.recommendation_recommendation USING btree (reviewed_by_id);


--
-- Name: recommendation_userfeedback_recommendation_id_7fa6f5a1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recommendation_userfeedback_recommendation_id_7fa6f5a1 ON public.recommendation_userfeedback USING btree (recommendation_id);


--
-- Name: recommendation_userfeedback_user_id_6d4568e9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recommendation_userfeedback_user_id_6d4568e9 ON public.recommendation_userfeedback USING btree (user_id);


--
-- Name: accounts_profile accounts_profile_user_id_49a85d32_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_49a85d32_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_activitylog core_activitylog_user_id_8705e516_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_activitylog
    ADD CONSTRAINT core_activitylog_user_id_8705e516_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_disease core_disease_crop_id_44be9f47_fk_core_crop_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_disease
    ADD CONSTRAINT core_disease_crop_id_44be9f47_fk_core_crop_id FOREIGN KEY (crop_id) REFERENCES public.core_crop(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_feedback core_feedback_user_id_630c6a53_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_feedback
    ADD CONSTRAINT core_feedback_user_id_630c6a53_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_notification core_notification_user_id_6e341aac_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_notification
    ADD CONSTRAINT core_notification_user_id_6e341aac_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: detection_prediction detection_prediction_crop_id_94368a84_fk_core_crop_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detection_prediction
    ADD CONSTRAINT detection_prediction_crop_id_94368a84_fk_core_crop_id FOREIGN KEY (crop_id) REFERENCES public.core_crop(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: detection_prediction detection_prediction_disease_id_48775137_fk_core_disease_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detection_prediction
    ADD CONSTRAINT detection_prediction_disease_id_48775137_fk_core_disease_id FOREIGN KEY (disease_id) REFERENCES public.core_disease(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: detection_prediction detection_prediction_scan_image_id_a21415ad_fk_detection; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detection_prediction
    ADD CONSTRAINT detection_prediction_scan_image_id_a21415ad_fk_detection FOREIGN KEY (scan_image_id) REFERENCES public.detection_scanimage(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: detection_scanimage detection_scanimage_user_id_44e0895f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detection_scanimage
    ADD CONSTRAINT detection_scanimage_user_id_44e0895f_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: history_predictionhistory history_predictionhi_prediction_id_8af233c9_fk_detection; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.history_predictionhistory
    ADD CONSTRAINT history_predictionhi_prediction_id_8af233c9_fk_detection FOREIGN KEY (prediction_id) REFERENCES public.detection_prediction(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: history_predictionhistory history_predictionhistory_user_id_fb641484_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.history_predictionhistory
    ADD CONSTRAINT history_predictionhistory_user_id_fb641484_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendation_recommendation recommendation_recom_disease_id_d327a144_fk_core_dise; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_recommendation
    ADD CONSTRAINT recommendation_recom_disease_id_d327a144_fk_core_dise FOREIGN KEY (disease_id) REFERENCES public.core_disease(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendation_recommendation recommendation_recom_prediction_id_a0033bba_fk_detection; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_recommendation
    ADD CONSTRAINT recommendation_recom_prediction_id_a0033bba_fk_detection FOREIGN KEY (prediction_id) REFERENCES public.detection_prediction(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendation_recommendation recommendation_recom_reviewed_by_id_2f4297d3_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_recommendation
    ADD CONSTRAINT recommendation_recom_reviewed_by_id_2f4297d3_fk_auth_user FOREIGN KEY (reviewed_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendation_userfeedback recommendation_userf_recommendation_id_7fa6f5a1_fk_recommend; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_userfeedback
    ADD CONSTRAINT recommendation_userf_recommendation_id_7fa6f5a1_fk_recommend FOREIGN KEY (recommendation_id) REFERENCES public.recommendation_recommendation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendation_userfeedback recommendation_userfeedback_user_id_6d4568e9_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_userfeedback
    ADD CONSTRAINT recommendation_userfeedback_user_id_6d4568e9_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--


