# Generated by Django 5.2.16 on 2026-07-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='needs_content',
            field=models.BooleanField(default=False, help_text='True if this disease was auto-created from model class data and still needs KB content filled in.'),
        ),
        migrations.AddField(
            model_name='disease',
            name='raw_class_name',
            field=models.CharField(blank=True, help_text='Exact class-folder name used during training (for robust ML->DB mapping).', max_length=160),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='disease',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='disease',
            unique_together={('crop', 'name'), ('crop', 'slug')},
        ),
    ]
