from django.db import models
from django.contrib.auth.models import User
from detection.models import Prediction, Disease


class Recommendation(models.Model):
    """Store recommendations for predictions"""
    URGENCY_CHOICES = [
        ("urgent", "Urgent"),
        ("moderate", "Moderate"),
        ("normal", "Normal"),
        ("none", "None"),
    ]

    prediction = models.OneToOneField(Prediction, on_delete=models.CASCADE, related_name="recommendation")
    disease = models.ForeignKey(Disease, on_delete=models.SET_NULL, null=True, blank=True)
    
    treatment_steps = models.TextField()
    prevention_steps = models.TextField()
    urgency = models.CharField(max_length=10, choices=URGENCY_CHOICES, default="normal")

    # Structured bilingual advice generated by the RAG engine (recommendation/rag.py),
    # grounded strictly in the Disease knowledge-base row. Cached here so the LLM is
    # only called once per prediction, not on every page view.
    # Shape: {"en": {summary, symptoms, causes, organic_treatment, chemical_treatment,
    #                prevention, severity_note, expert_advice}, "ur": {...same keys...}}
    ai_content = models.JSONField(default=dict, blank=True)
    ai_content_generated_at = models.DateTimeField(null=True, blank=True)
    ai_generation_error = models.TextField(
        blank=True, help_text="Set if the RAG/LLM call failed; the KB fields are shown as a fallback."
    )

    additional_notes = models.TextField(blank=True)
    expert_reviewed = models.BooleanField(default=False)
    reviewed_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="reviewed_recommendations")
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"Recommendation for {self.prediction.id}"


class UserFeedback(models.Model):
    """Store user feedback on recommendations"""
    FEEDBACK_CHOICES = [
        ("helpful", "Helpful"),
        ("not_helpful", "Not Helpful"),
        ("partially_helpful", "Partially Helpful"),
    ]

    recommendation = models.ForeignKey(Recommendation, on_delete=models.CASCADE, related_name="feedback")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    feedback_type = models.CharField(max_length=20, choices=FEEDBACK_CHOICES)
    comment = models.TextField(blank=True)
    rating = models.IntegerField(choices=[(i, str(i)) for i in range(1, 6)], null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        unique_together = ("recommendation", "user")

    def __str__(self):
        return f"{self.user.username} - {self.recommendation.id}"
