# Generated by Django 5.2.16 on 2026-07-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='ai_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='ai_content_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='ai_generation_error',
            field=models.TextField(blank=True, help_text='Set if the RAG/LLM call failed; the KB fields are shown as a fallback.'),
        ),
    ]
